# Generated by Django 5.0.6 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_moisture', models.FloatField()),
                ('target_moisture', models.FloatField()),
                ('max_moisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='aw_moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_moisture', models.FloatField()),
                ('target_moisture', models.FloatField()),
                ('max_moisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('more_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tg_moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_moisture', models.FloatField()),
                ('target_moisture', models.FloatField()),
                ('max_moisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='wb_moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_moisture', models.FloatField()),
                ('target_moisture', models.FloatField()),
                ('max_moisture', models.FloatField()),
            ],
        ),
    ]
