# Generated by Django 5.0.6 on 2024-07-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gt_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_min', models.FloatField()),
                ('aw_target', models.FloatField()),
                ('aw_max', models.FloatField()),
                ('aw_actual', models.FloatField()),
                ('aw_sample', models.FloatField()),
                ('w_actual', models.FloatField()),
                ('w_sample', models.FloatField()),
                ('tg_actual', models.FloatField()),
                ('tg_sample', models.FloatField()),
                ('spraydry_min', models.FloatField()),
                ('spraydry_target', models.FloatField()),
                ('spraydry_max', models.FloatField()),
                ('sfb_min', models.FloatField()),
                ('sfb_target', models.FloatField()),
                ('sfb_max', models.FloatField()),
                ('tg_dry', models.FloatField()),
                ('k', models.FloatField()),
            ],
        ),
    ]
