# Generated by Django 5.0.6 on 2024-07-18 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.FloatField()),
                ('casein', models.FloatField()),
                ('whey_protein', models.FloatField()),
                ('lactose', models.FloatField()),
                ('GOS', models.FloatField()),
                ('PDX', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.FloatField()),
                ('casein', models.FloatField()),
                ('whey_protein', models.FloatField()),
                ('lactose', models.FloatField()),
                ('GOS', models.FloatField()),
                ('PDX', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Final_Couchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('water_min', models.FloatField()),
                ('casein', models.FloatField()),
                ('whey_protein', models.FloatField()),
                ('lactose', models.FloatField()),
                ('GOS', models.FloatField()),
                ('PDX', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('water_min', models.FloatField()),
                ('casein', models.FloatField()),
                ('whey_protein', models.FloatField()),
                ('lactose', models.FloatField()),
                ('GOS', models.FloatField()),
                ('PDX', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
