# Generated by Django 5.0.6 on 2024-06-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_couchman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulation',
            old_name='water',
            new_name='water_min',
        ),
    ]
