# Generated by Django 5.0.6 on 2024-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_couchman', '0002_rename_water_formulation_water_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('more_info', models.CharField(max_length=200)),
            ],
        ),
    ]
