# Generated by Django 5.0.6 on 2024-06-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cp',
            old_name='gos',
            new_name='GOS',
        ),
        migrations.RenameField(
            model_name='cp',
            old_name='pdx',
            new_name='PDX',
        ),
        migrations.RenameField(
            model_name='formulation',
            old_name='gos',
            new_name='GOS',
        ),
        migrations.RenameField(
            model_name='formulation',
            old_name='pdx',
            new_name='PDX',
        ),
        migrations.RenameField(
            model_name='tg',
            old_name='gos',
            new_name='GOS',
        ),
        migrations.RenameField(
            model_name='tg',
            old_name='pdx',
            new_name='PDX',
        ),
        migrations.RemoveField(
            model_name='formulation',
            name='lactose',
        ),
    ]
