# Generated by Django 5.0.6 on 2024-08-05 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryairAH', models.FloatField(default=0.0)),
                ('primaryair', models.FloatField(default=0.0)),
                ('primaryinletT', models.FloatField(default=0.0)),
                ('outletairT', models.FloatField(default=0.0)),
                ('sfbair', models.FloatField(default=0.0)),
                ('sfbinletT', models.FloatField(default=0.0)),
                ('roofcoolingair', models.FloatField(default=0.0)),
                ('roofcoolingT', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('totalsolids', models.FloatField(default=0.0)),
                ('moisture', models.FloatField(default=0.0)),
                ('sfbinletAH', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfb_inlet_rh', models.FloatField()),
                ('outlet_air_ah', models.FloatField()),
                ('outlet_air_rh', models.FloatField()),
                ('dummy_outlet_air_rh', models.FloatField()),
                ('dummy_outlet_air_t', models.FloatField()),
                ('production_rate', models.FloatField()),
                ('barometric_pressure', models.FloatField()),
                ('input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mass_balance.inputdata')),
            ],
        ),
    ]
