# Generated by Django 5.0.6 on 2024-08-05 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NozzleCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nozzles', models.FloatField()),
                ('swirl_number', models.CharField(max_length=50)),
                ('orifice_number', models.FloatField()),
                ('operating_pressure', models.FloatField()),
                ('lsg', models.FloatField()),
                ('lpcs', models.FloatField()),
                ('ppcm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NozzleTDLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_flow_rate', models.FloatField()),
                ('powder_flow_rate', models.FloatField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nozzle.nozzlecalculation')),
            ],
        ),
        migrations.CreateModel(
            name='NozzleTDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_flow_rate', models.FloatField()),
                ('spray_angle', models.FloatField()),
                ('droplet_size', models.FloatField()),
                ('powder_flow_rate', models.FloatField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nozzle.nozzlecalculation')),
            ],
        ),
    ]
